Text:
  type:
    type: resource type
    value: text
    source:
      value: MODS resource types
  subtypes:
    Article:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Government document:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Policy brief:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Preprint:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Report:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Technical report:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Thesis:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Working paper:
      - type: resource type
        value: text
        source:
          value: MODS resource types
Data:
  type:
    type: resource type
    value: software, multimedia
    source:
      value: MODS resource types
  subtypes:
    3D model:
      - type: resource type
        value: three dimensional object
        source:
          value: MODS resource types
    Database:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Documentation:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Geospatial data:
      - type: resource type
        value: cartographic
        source:
          value: MODS resource types
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Image:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
    Tabular data:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Text corpus:
      - type: resource type
        value: text
        source:
          value: MODS resource types
Software/Code:
  type:
    type: resource type
    value: software, multimedia
    source:
      value: MODS resource types
  subtypes:
    Code:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Documentation:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Game:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
Image:
  type:
    type: resource type
    value: still image
    source:
      value: MODS resource types
  subtypes:
    CAD:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
    Map:
      - type: resource type
        value: cartographic
        source:
          value: MODS resource types
    Photograph:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
    Poster:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
    Presentation slides:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
Sound:
  type:
    type: resource type
    value: sound recording
    source:
      value: MODS resource types
  subtypes:
    Interview:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Oral history:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Podcast:
      - type: resource type
        value: Podcasts
        source:
          value: MODS resource types
    Speech:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
Video:
  type:
    type: resource type
    value: moving image
    source:
      value: MODS resource types
  subtypes:
    Conference session:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Documentary:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Event:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Oral history:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Performance:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
Music:
  type:
    type: resource type
    value: music
    source:
      value: MODS resource types
  subtypes:
    Data:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Image:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
    MIDI:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Musical transcription:
      - type: resource type
        value: notated music
        source:
          value: MODS resource types
    Notated music:
      - type: resource type
        value: notated music
        source:
          value: MODS resource types
    Piano roll:
      - type: resource type
        value: sound recording-musical
        source:
          value: MODS resource types
    Software/Code:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Sound:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Text:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Video:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
Mixed Materials:
  type:
    type: resource type
    value: mixed material
    source:
      value: MODS resource types
  subtypes:
    Data:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Image:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
    Software/Code:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Sound:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Text:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Video:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
General:
  subtypes:
    Animation:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Book:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Book chapter:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Broadcast:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Correspondence:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    # TODO: How to deal with this duplication?
    Course/instructional materials:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Course/instructional materials:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Documentary:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Dramatic performance:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Essay:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    # TODO: How to deal with this duplication?
    Ethnography:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Ethnography:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Experimental audio/video:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    # TODO: How to deal with this duplication?
    Field recording:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Field recording:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Journal/periodical issue:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Manuscript:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    MIDI:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Musical transcription:
      - type: resource type
        value: notated music
        source:
          value: MODS resource types
    Narrative film:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Notated music:
      - type: resource type
        value: notated music
        source:
          value: MODS resource types
    Other spoken word:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Piano roll:
      - type: resource type
        value: sound recording-musical
        source:
          value: MODS resource types
    Poetry reading:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Poster:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Presentation recording:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Presentation slides:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Questionnaire:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Remote sensing imagery:
      - type: resource type
        value: still image
        source:
          value: MODS resource types
    Software:
      - type: resource type
        value: software, multimedia
        source:
          value: MODS resource types
    Sound recording:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Speaker notes:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Speech:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Story:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Syllabus:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    Transcript:
      - type: resource type
        value: text
        source:
          value: MODS resource types
    # TODO: How to deal with this duplication?
    Unedited recording:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Unedited recording:
      - type: resource type
        value: sound recording
        source:
          value: MODS resource types
    Video art:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    Video recording:
      - type: resource type
        value: moving image
        source:
          value: MODS resource types
    White paper:
      - type: resource type
        value: text
        source:
          value: MODS resource types
