Text:
  Article:
    - type: genre
      value: articles
      uri: http://vocab.getty.edu/aat/300048715
      source:
        code: aat
  Book:
    - type: genre
      value: books
      uri: http://vocab.getty.edu/aat/300028051
      source:
        code: aat
  Book chapter:
    - type: genre
      value: Book chapters
  Correspondence:
    - type: genre
      value: correspondence
      uri: http://vocab.getty.edu/aat/300026877
      source:
        code: aat
  Essay:
    - type: genre
      value: Essays
      uri: http://id.loc.gov/authorities/genreForms/gf2014026094
      source:
        code: lcgft
  Government document:
    - type: genre
      value: government records
      uri: http://vocab.getty.edu/aat/300027777
      source:
        code: aat
  Journal/periodical:
    - type: genre
      value: Periodicals
      uri: http://id.loc.gov/authorities/genreForms/gf2014026139
  Manuscript:
    - type: genre
      value: manuscripts (documents)
      uri: http://vocab.getty.edu/aat/300028569
      source:
        code: aat
  Poster:
    - type: genre
      value: Posters
      uri: http://id.loc.gov/authorities/genreForms/gf2014026152
      source:
        code: lcgft
  Presentation slides:
    - type: genre
      value: Presentation slides
  Report:
    - type: genre
      value: reports
      uri: http://vocab.getty.edu/aat/300027267
      source:
        code: aat
  Speech:
    - type: genre
      value: Speeches
      uri: http://id.loc.gov/authorities/genreForms/gf2011026363
      source:
        code: lcgft
  Syllabus:
    - type: genre
      value: Outlines and syllabi
      uri: http://id.loc.gov/authorities/genreForms/gf2014026136
      source:
        code: lcgft
  Teaching materials:
    - type: genre
      value: Instructional and educational works
      uri: http://id.loc.gov/authorities/genreForms/gf2014026114
      source:
        code: lcgft
  Technical report:
    - type: genre
      value: Technical reports
      uri: http://id.loc.gov/authorities/genreForms/gf2015026093
      source:
        code: lcgft
  Thesis:
    - type: genre
      value: Academic theses
      uri: http://id.loc.gov/authorities/genreForms/gf2014026039
      source:
        code: lcgft
  Transcription:
    - type: genre
      value: transcripts
      uri: http://vocab.getty.edu/aat/300027388
      source:
        code: aat
  White paper:
    - type: genre
      value: grey literature
      uri: http://vocab.getty.edu/aat/300256200
      source:
        code: aat
  Working paper:
    - type: genre
      value: grey literature
      uri: http://vocab.getty.edu/aat/300256200
      source:
        code: aat
Data:
  3D model:
    - type: genre
      value: Three dimensional scan
  Audio:
    - type: genre
      value: dataset
    - type: genre
      value: Sound recordings
      uri: http://id.loc.gov/authorities/genreForms/gf2011026594
      source:
        code: lcgft
  Database:
    - type: genre
      value: dataset
    - type: genre
      value: Databases
      uri: http://id.loc.gov/authorities/genreForms/gf2014026081
      source:
        code: lcgft
  GIS:
    - type: genre
      value: dataset
    - type: genre
      value: Geographic information systems
      uri: http://id.loc.gov/authorities/genreForms/gf2011026294
      source:
        code: lcgft
  Image:
    - type: genre
      value: dataset
    - type: genre
      value: Pictures
      uri: http://id.loc.gov/authorities/genreForms/gf2017027251
      source:
        code: lcgft
  Questionnaire:
    - type: genre
      value: dataset
    - type: genre
      value: Questionnaires
      uri: http://id.loc.gov/authorities/genreForms/gf2018026144
      source:
        code: lcgft
  Remote sensing imagery:
    - type: genre
      value: dataset
    - type: genre
      value: Remote-sensing images
      uri: http://id.loc.gov/authorities/genreForms/gf2011026530
      source:
        code: lcgft
  Software/code:
    - type: genre
      value: dataset
    - type: genre
      value: software
      uri: http://vocab.getty.edu/aat/300028566
      source:
        code: aat
  Statistical model:
    - type: genre
      value: dataset
    - type: genre
      value: mathematical models
      uri: http://vocab.getty.edu/aat/300065075
      source:
        code: aat
  Tabular data:
    - type: genre
      value: dataset
    - type: genre
      value: Tables (Data)
      uri: http://id.loc.gov/authorities/genreForms/gf2014026186
      source:
        code: lcgft
  Text corpus:
    - type: genre
      value: dataset
    - type: genre
      value: Text corpora
      uri: http://id.loc.gov/authorities/genreForms/gf2019026083
      source:
        code: lcgft
  Text documentation:
    - type: genre
      value: dataset
    - type: genre
      value: Data dictionaries
      uri: http://id.loc.gov/authorities/genreForms/gf2014026080
      source:
        code: lcgft
  Video:
    - type: genre
      value: dataset
    - type: genre
      value: moving images
      uri: http://vocab.getty.edu/aat/300263857
      source:
        code: aat
Software or Code:
  Code:
    - type: genre
      value: programs (computer)
      uri: http://vocab.getty.edu/aat/300312188
      source:
        code: aat
  Documentation:
    - type: genre
      value: technical manuals
      uri: http://vocab.getty.edu/aat/300026413
      source:
        code: aat
  Game:
    - type: genre
      value: video games
      uri: http://vocab.getty.edu/aat/300256888
      source:
        code: aat
Image:
  CAD:
    - type: genre
      value: computer-aided designs (visual works)
      uri: http://vocab.getty.edu/aat/300418056
      source:
        code: aat
  Map:
    - type: genre
      value: Maps
      uri: http://id.loc.gov/authorities/genreForms/gf2011026387
      source:
        code: lcgft
  Photograph:
    - type: genre
      value: Photographs
      uri: http://id.loc.gov/authorities/genreForms/gf2017027249
      source:
        code: lcgft
  Poster:
    - type: genre
      value: Posters
      uri: http://id.loc.gov/authorities/genreForms/gf2014026152
      source:
        code: lcgft
  Presentation slides:
    - type: genre
      value: Presentation slides
Sound:
  Course/instruction:
    - type: genre
      value: Instructional and educational works
      uri: http://id.loc.gov/authorities/genreForms/gf2014026114
      source:
        code: lcgft
  Documentary:
    - type: genre
      value: documentaries (documents)
      uri: http://vocab.getty.edu/aat/300249172
      source:
        code: aat
  Dramatic performance:
    - type: genre
      value: Drama
      uri: http://id.loc.gov/authorities/genreForms/gf2014026297
      source:
        code: lcgft
  Ethnography:
    - type: genre
      value: Ethnographies
      uri: http://id.loc.gov/authorities/genreForms/gf2018026013
      source:
        code: lcgft
  Field recordings:
    - type: genre
      value: Field recordings
      uri: http://id.loc.gov/authorities/genreForms/gf2011026253
      source:
        code: lcgft
  Interview:
    - type: genre
      value: Interviews
      uri: http://id.loc.gov/authorities/genreForms/gf2014026115
      source:
        code: lcgft
  MIDI:
    - type: genre
      value: MIDI (information technology)
      uri: http://vocab.getty.edu/aat/300266746
      source:
        code: aat
  Musical notation:
    - type: genre
      value: Notated music
      uri: http://id.loc.gov/authorities/genreForms/gf2014027184
      source:
        code: lcgft
  Musical performance:
    - type: genre
      value: musical performances
      uri: http://vocab.getty.edu/aat/300262956
      source:
        code: aat
  Oral history:
    - type: genre
      value: Oral histories
      uri: http://id.loc.gov/authorities/genreForms/gf2011026431
      source:
        code: lcgft
  Other spoken word:
    - type: genre
      value: Spoken word
  Podcast:
    - type: genre
      value: Podcasts
      uri: http://id.loc.gov/authorities/genreForms/gf2011026450
      source:
        code: lcgft
  Poetry reading:
    - type: genre
      value: Poetry
      uri: http://id.loc.gov/authorities/genreForms/gf2014026481
      source:
        code: lcgft
  Speech:
    - type: genre
      value: Speeches
      uri: http://id.loc.gov/authorities/genreForms/gf2011026363
      source:
        code: lcgft
  Story:
    - type: genre
      value: Fiction
      uri: http://id.loc.gov/authorities/genreForms/gf2014026339
      source:
        code: lcgft
  Transcript:
    - type: genre
      value: transcripts
      uri: http://vocab.getty.edu/aat/300027388
      source:
        code: aat
  Unedited recording:
    - type: genre
      value: Unedited sound recordings
Video:
  Animation:
    - type: genre
      value: animations (visual works)
      uri: http://vocab.getty.edu/aat/300411663
      source:
        code: aat
  Broadcast:
    - type: genre
      value: Television programs
      uri: http://id.loc.gov/authorities/genreForms/gf2011026673
      source:
        code: lcgft
  Conference session:
    - type: genre
      value: Conference sessions
  Course/instruction:
    - type: genre
      value: Instructional and educational works
      uri: http://id.loc.gov/authorities/genreForms/gf2014026114
      source:
        code: lcgft
  Documentary:
    - type: genre
      value: Documentary films
      uri: http://id.loc.gov/authorities/genreForms/gf201102620
      source:
        code: lcgft
  Ethnography:
    - type: genre
      value: Ethnographic films
      uri: http://id.loc.gov/authorities/genreForms/gf2011026232
      source:
        code: lcgft
  Event:
    - type: genre
      value: events (activities)
      uri: http://vocab.getty.edu/aat/300069084
      source:
        code: aat
  Experimental:
    - type: genre
      value: Experimental films
      uri: http://id.loc.gov/authorities/genreForms/gf2011026235
      source:
        code: lcgft
  Field recordings:
    - type: genre
      value: Field recordings
      uri: http://id.loc.gov/authorities/genreForms/gf2011026253
      source:
        code: lcgft
  Narrative film:
    - type: genre
      value: Fiction films
      uri: http://id.loc.gov/authorities/genreForms/gf2011026250
      source:
        code: lcgft
  Oral history:
    - type: genre
      value: Oral histories
      uri: http://id.loc.gov/authorities/genreForms/gf2011026431
      source:
        code: lcgft
  Performance:
    - type: genre
      value: Filmed performances
      uri: http://id.loc.gov/authorities/genreForms/gf2011026276
      source:
        code: lcgft
  Presentation:
    - type: genre
      value: presentations (communicative events)
      uri: http://vocab.getty.edu/aat/300258677
      source:
        code: aat
  Unedited footage:
    - type: genre
      value: Unedited footage
      uri: http://id.loc.gov/authorities/genreForms/gf2011026712
      source:
        code: lcgft
  Video art:
    - type: genre
      value: Video art
      uri: http://id.loc.gov/authorities/genreForms/gf2017027265
      source:
        code: lcgft
Mixed materials:
  Data:
    - type: genre
      value: dataset
    - type: genre
      value: Data sets
      uri: http://id.loc.gov/authorities/genreForms/gf2018026119
      source:
        code: lcgft
  Image:
    - type: genre
      value: Pictures
      uri: http://id.loc.gov/authorities/genreForms/gf2017027251
      source:
        code: lcgft
  Software/Code:
    - type: genre
      value: software
      uri: http://vocab.getty.edu/aat/300028566
      source:
        code: aat
  Sound:
    - type: genre
      value: Sound recordings
      uri: http://id.loc.gov/authorities/genreForms/gf2011026594
      source:
        code: lcgft
  Text:
    - type: genre
      value: texts (documents)
      uri: http://vocab.getty.edu/aat/300263751
      source:
        code: aat
  Video:
    - type: genre
      value: moving images
      uri: http://vocab.getty.edu/aat/300263857
      source:
        code: aat
