default: &default
  adapter: postgresql
  encoding: unicode
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>"
  host: "<%= ENV.fetch('DATABASE_HOSTNAME', 'localhost') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', 5432) %>"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME', 'h2_development') %>"

test:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME', 'h2_test') %>"

production:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME', 'h2_production') %>"
